title: mniip.com
domain: mniip.com
url: "https://mniip.com/"
baseurl: ""
author: mniip

markdown: kramdown
locale: en_US

defaults:
  - scope:
      path: ""
    values:
      layout: default
      excerpt_separator: "<!-- more -->"

collections:
  posts:
    output: true
    permalink: /:collection/:name

feed: {}

plugins:
  - jekyll-feed
