title: mniip.com
domain: mniip.com
url: "https://mniip.com/"
baseurl: ""

markdown: kramdown
locale: en_US

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections:
  posts:
    output: true
    permalink: /:collection/:name

plugins: []
